### PR TITLE
Pass2: gettings packs from github etc.

### PR DESCRIPTION
**Pull request by infograf768**
Adding vendor folder.
Getting packs automatically from Github. Added 2 new fields to retrieve the packs.
Corrected a lot of cs in the library. Adding function getReleases().
Taking off a few useless index.html.
Modifying ini file

### CODE REVIEW

**Comment by infograf768** [comment]
This is not final obviously, but things should look clearer.
We can, if we like, add a new array for versions 3.0.0, 3.1.0 etc. until 3.7.2 which is taken care of automatically.
Would be good to understand why packs before 3.7.2 are not proposed automatically when looking for github releases.

**Comment by infograf768** [comment]
@Bakual 
I guess there should be some changes to .gitignore
Also, would be nice to add Travis here.

**Comment by Bakual** [comment]
I know how we can add the service Travis to the repo, but without tests and configuration it will not do anything. And I honestly don't know how to set up Travis to do anything :smile:

**Comment by infograf768** [comment]
ROTFLOL

**Comment by Bakual** [comment]
Why do you mean to change .gitignore? The vendor folder is fine. But of course if you OS or IDE does add some folders you want to ignore, you can add them as well.

**Comment by infograf768** [comment]
I was referring to your PR for com_localise
See https://github.com/joomla-projects/com_localise/pull/322/files

**Comment by Bakual** [comment]
Ah true, we can exclude those folders here as well.

Edit: Looking at the folders, I don't see them anymore in the list of files here. Did you remove them yourself or has the Github repo changed?

**Comment by infograf768** [comment]
What do you mean by looking at the folders? Which folders?

**Comment by infograf768** [comment]
For .gitignore I let you make a PR.
For the moment, it only contains .idea

**Comment by Bakual** [comment]
In this PR I don't see the /Tests and /.github folders we ignore in com_localise. That's why I asked if you excluded (didn't commit) those manually.

**Comment by infograf768** [comment]
I just picked the vendor folder as is from com_localise.

**Comment by Bakual** [comment]
Ah :)

**Comment by Bakual** [comment]
We can do the gitignore thing then at the same time we properly do the composer stuff. No hurry.

**Comment by infograf768** [comment]
Great
Let's wait for Mig tests.

I can easily add the former 3.x releases if necessary (just tested) by adding something like
```
		$olderpacks = array('3.7.1', '3.7.0', '3.6.0', '3.5.0', '3.4.0', '3.3.0', '3.2.0', '3.1.0', '3.0.0');

		foreach ($olderpacks as $olderpack)
		{	
			$options[] = JHtml::_('select.option', $olderpack, 'Joomla ' . $olderpack,
							array('option.attr' => 'attributes')
							);
		}
```
Not sure it is really necessary

**Pull request merged**
