### PR TITLE
Composer

### LINKED ISSUE #6: Error Cannot redeclare class ComposerAutoloaderInit
Today i have installed this new module update and i have found a conflic with another module called "mod_translations" that i am starting.

The issue is due both use the "vendor" folder to make run calls to github and be able to update the joomla releases field on the fly.

i have solved on my module adding:

```
		if (!class_exists('ComposerAutoloaderInit4160684424009696d59dcdb51070d003'))
		{
		         require_once JPATH_ROOT . '/modules/mod_translations/vendor/autoload.php';
		}
```

I think is good idea make similar patch to mod_ttm_diff_tool "vendor" calls to avoid future crashes.

Regards

### PR DESCRIPTION
**Pull request by Bakual**
Proper implementation of composer. Vendor folder updated using `composer install`.
This should fix #6 

@infograf768 Can you try if that works.

### CODE REVIEW

**Comment by infograf768** [comment]
will test as soon as i have a correct internet connexion

**Comment by infograf768** [comment]
OK, This works fine.
Note: Taking into account all the changes done in the vendor folder, would'nt that mean that the com_localise vendor folder should also be modified?

**Comment by Bakual** [comment]
The changes come from a newer version of JGithub. In com_localise it's 1.5.3 (https://github.com/joomla-projects/com_localise/blob/develop/component/composer.lock#L67) and here we got 1.6.0.
So yes, we eventually have to update composer stuff in com_localise :smile:

**Comment by infograf768** [comment]
Thanks!

**Pull request merged**
