### PR TITLE
Code style, using sprintf, other

### PR DESCRIPTION
**Pull request by infograf768**
Using sprintf instead of multiple JText.
Thus modifying/adding a few ini strings.
A few more code style.

@valc Now you can add a PR for es-ES ini file.
I wonder what to do with this one btw:
`MOD_TTM_DIFF_TOOL_OTF_ORIENTATIVE_ZIPBALL_URL="* Orientative URL. Type zipball package can to be in continued rolling release and the id within the package name will be changed frequently."`
As this shows when we use staging as target. Not sure we even need it at all.

### CODE REVIEW

**Comment by infograf768** [comment]
Also modified MOD_TTM_DIFF_TOOL_OTF_ORIENTATIVE_ZIPBALL_URL

**Comment by Valc** [comment]
Hi:
@infograf768 
MOD_TTM_DIFF_TOOL_OTF_ORIENTATIVE_ZIPBALL_URL
This only try to make notice that if user follow the download link maybe the content based on the reported diff has changes due this case is not a "frozen" release (such as stable, beta or similars, that the language files have not changes one time are downloads).
If not required explain the issue then can be deleted XD

Regards.

**Comment by infograf768** [comment]
@Valc 
I had changed it to
 +MOD_TTM_DIFF_TOOL_OTF_ORIENTATIVE_ZIPBALL_URL="* Indicative. The development package is modified continuously and the id within the package name is changed frequently." 

Will modify it to
 +MOD_TTM_DIFF_TOOL_OTF_ORIENTATIVE_ZIPBALL_URL="* The development package is modified continuously which may change the diff. "

**Comment by infograf768** [comment]
@Valc You can now make a PR to update es-ES for this one.

**Pull request merged**
